[programs.localnet]
mortys = "Bqi8EqoLJxT2eojRBk6Ta4xKnBKxfXguRk1cxu6STwRZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/codespace/.config/solana/id.json"


[scripts]
test = "node tests/main.js" 